export const events = [
    {
    id: 1,
    title: "Adiparampara - A Journey Through Traditional Games 🎲",
    image: "/EventCard/adi.png",
    date: "1 Mar 2025",
    link: "https://example.com/phenomenon-labs",
    tags: ["Event", "Culture", "Inauguration"], 
    description: "Adiparampara is a vibrant festival that brings together the essence of India’s rich heritage through a series of exciting events, including Kridotsav, Aakriti, Kurukshetra 2.0, Rasamaya Manjari, Chakravyuh, and Vastra Mahotsav. Each event adds a unique touch to the celebration, creating an immersive experience  ",
    },
    {
    id: 2,
    title: "Maha Shivaratri (महाशिवरात्रि) Celebration!",
    image: "/EventCard/shivratri.png",
    date: "26 Feb 2025",
    link: "https://example.com/zajno",
    tags: ["Festival", "Culture","Shiva", "Tradition"], 
    description: "Join us for a divine Maha Shivaratri celebration, organized by SMILE Club, Hindi Evam Sanskrit Club, and Utkrishth Bharat Club! Experience the spiritual energy with traditional rituals, soulful music, and a night filled with devotion. Let’s come together in unity and joy to embrace the essence of Lord Shiva! 🙏✨",
    },
    {
    id: 3,
    title: "AYODHYA RAM PUNAH AAGMAN",
    image: "/EventCard/ram.png",
    date: "22 Jan 2025",
    link: "https://example.com/ascended",
    tags: ["Festival", "Culture", "Temple", "Rama", "Tradition"], 
    description: "Join us as Utkrishta Bharat and SMILE Club celebrate the Ayodhya Ram Punah Aagman Vaarshikotsav, a spiritual and cultural tribute to Lord Ram. Experience divine recitations, soulful music, and traditional performances that reflect the richness of our heritage. Let’s come together in devotion and joy!",
    },
    {
    id: 4,
    title: "ADIPARAMPARA: KRIDOTSAV",
    image: "/EventCard/kridotsav.png",
    date: "1 Mar 2025",
    link: "https://example.com/ascended",
    tags: ["Event", "Fun", "Games", "Tradition"], 
    description: "🚨 Calling all nostalgia lovers, traditional game enthusiasts, and fun seekers! 🚨Get ready to relive the golden era of childhood* with KRIDOTSAV – a spectacular celebration of ancient Indian household games! 🎲🏏⚡",
    },
    {
    id: 5,
    title: "ADIPARAMPARA: AAKRITI",
    image: "/EventCard/aakriti.png",
    date: "1 Mar 2025",
    link: "https://example.com/ascended",
    tags: ["Creativity", "Games", "Tradition"], 
    description: "🚨 Calling all artists, dreamers, and creative souls! 🚨Get ready to bring your imagination to life at AAKRITI – an exciting Painting Event where colors meet creativity! 🖌✨ Whether you're a seasoned artist or just love to express yourself through art, this is your chance to shine! 🌟",
    },
    {
    id: 6,
    title: "ADIPARAMPARA: KURUKSHETRA 2.0",
    image: "/EventCard/kurukshetra.png",
    date: "1 Mar 2025",
    link: "https://example.com/ascended",
    tags: ["Brilliant", "Games", "Mind"], 
    description: "🌟KURUKSHETRA 2.0 : The Ultimate Quiz on Ramayana & Mahabharata🌟 Part of 💫AADIPARAMPARA 💫 SMILE Club's Flagship EventJoin ✨SMILE Club’s ✨grand epic challenge! Test your wisdom, strategy, and divine knowledge.🏹 Battle of the Brightest – Compete with fellow warriors and claim victory!",
    },
    {
    id: 7,
    title: "ADIPARAMPARA: CHAKRAVIYUH",
    image: "/EventCard/chakraviyuh.png",
    date: "1 Mar 2025",
    link: "https://example.com/ascended",
    tags: ["Strategy", "Event", "Treasure"], 
    description: "Get ready to dive into the legendary world of Mahabharat like never before! 🏹⚔️ We’re thrilled to announce our very first Treasure Hunt Event – a thrilling journey filled with riddles, clues, and hidden treasures inspired by the greatest epic of all time! 🕵️‍♂️✨",
    },
    {
    id: 8,
    title: "ADIPARAMPARA: RASAMAYA MANJARI",
    image: "/EventCard/Rasamaya.png",
    date: "1 Mar 2025",
    link: "https://example.com/ascended",
    tags: ["Emotions", "Aesthetic", "Event"], 
    description: "🍹 Savor the Flavors – Enjoy Rose Milk, sugar cane juice and variery of mouth watering delicacies!🥒 Dare to Drink? – Conquer the Bitter Gourd Juice Challenge & win exciting prizes!🎯 Game On! – Play thrilling games & win exciting prizes!🏆 Contests & Competitions – Taste, speed & skill challenges with prizes & coupons!",
    },
    {
    id: 9,
    title: "ADIPARAMPARA: VASTRA MAHOTSAV",
    image: "/EventCard/vastra.png",
    date: "1 Mar 2025",
    link: "https://example.com/ascended",
    tags: ["Clothes", "Culture", "Competition", "Tradition"], 
    description: "Join SMILE Club’s grand cultural celebration! Unleash your inner royalty and embrace the elegance of *AdiParampara* traditions. Let’s turn Instagram into a runway of heritage!",
    },
];
