export const events = [
    {
    id: 1,
    title: "Event 1",
    image: "event.jpg",
    category: "Meditation",
    date: "2022-08-20",
    author: "Sharma Ji",
    link: "https://example.com/phenomenon-labs",
    description: "Join us for an exciting event filled with creativity and inspiration.",
    },
    {
    id: 2,
    title: "Event 2",
    image: "event2.jpg",
    category: "Meditation",
    date: "2022-08-20",
    author: "Sharma Ji",
    link: "https://example.com/zajno",
    description: "Explore innovative ideas and network with like-minded individuals.",
    },
    {
    id: 3,
    title: "Event 3",
    image: "event.jpg",
    category: "Meditation",
    date: "2022-08-20",
    author: "Sharma Ji",
    link: "https://example.com/ascended",
    description: "A deep dive into the latest trends and transformative experiences.",
    },
];